// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ResumeMicroservice.Api.Database;

#nullable disable

namespace ResumeMicroservice.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ResumeMicroservice.Api.Models.Resume", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AboutMe")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<long?>("DesiredSalary")
                        .HasColumnType("bigint");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patronymic")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("ReadyToMove")
                        .HasColumnType("boolean");

                    b.Property<string>("ResumeTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Resumes");
                });

            modelBuilder.Entity("ResumeMicroservice.Api.Models.Skills.Education", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EducationForm")
                        .HasColumnType("text");

                    b.Property<string>("EducationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EducationalInstitution")
                        .HasColumnType("text");

                    b.Property<Guid?>("ResumeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Specialization")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ResumeId");

                    b.ToTable("Education");
                });

            modelBuilder.Entity("ResumeMicroservice.Api.Models.Skills.EmployeeExperience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyPost")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("CurrentlyWorkHere")
                        .HasColumnType("boolean");

                    b.Property<string>("Responsibilities")
                        .HasColumnType("text");

                    b.Property<Guid?>("ResumeId")
                        .HasColumnType("uuid");

                    b.Property<string>("WorkingFromMonth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkingFromYear")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkingUntilMonth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkingUntilYear")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ResumeId");

                    b.ToTable("EmployeeExperience");
                });

            modelBuilder.Entity("ResumeMicroservice.Api.Models.Skills.ForeignLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LanguageProficiencyLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ResumeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ResumeId");

                    b.ToTable("ForeignLanguage");
                });

            modelBuilder.Entity("ResumeMicroservice.Api.Models.Skills.Education", b =>
                {
                    b.HasOne("ResumeMicroservice.Api.Models.Resume", null)
                        .WithMany("Educations")
                        .HasForeignKey("ResumeId");
                });

            modelBuilder.Entity("ResumeMicroservice.Api.Models.Skills.EmployeeExperience", b =>
                {
                    b.HasOne("ResumeMicroservice.Api.Models.Resume", null)
                        .WithMany("EmployeeExperience")
                        .HasForeignKey("ResumeId");
                });

            modelBuilder.Entity("ResumeMicroservice.Api.Models.Skills.ForeignLanguage", b =>
                {
                    b.HasOne("ResumeMicroservice.Api.Models.Resume", null)
                        .WithMany("ForeignLanguages")
                        .HasForeignKey("ResumeId");
                });

            modelBuilder.Entity("ResumeMicroservice.Api.Models.Resume", b =>
                {
                    b.Navigation("Educations");

                    b.Navigation("EmployeeExperience");

                    b.Navigation("ForeignLanguages");
                });
#pragma warning restore 612, 618
        }
    }
}
