services:
  web-mvc:
    container_name: web-mvc
    image: ${DOCKER_REGISTRY-}web-mvc
    build:
      context: .
      dockerfile: src/Web/Web.MVC/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 35121:8080

  gateway-api:
    container_name: gateway-api
    image: ${DOCKER_REGISTRY-}gateway-api
    build:
      context: .
      dockerfile: src/Gateway/Gateway.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 35122:8080

  account-microservice-api:
    container_name: account-microservice-api
    image: ${DOCKER_REGISTRY-}accountmicroservice-api
    build:
      context: .
      dockerfile: src/Microservices/Account/AccountMicroservice.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 35123:8080
    depends_on:
       postgres-account:
         condition: service_started
       gateway-api:
         condition: service_started
       kafka:
         condition: service_started

  bookmark-microservice-api:
    container_name: bookmark-microservice-api
    image: ${DOCKER_REGISTRY-}bookmarkmicroservice-api
    build:
      context: .
      dockerfile: src/Microservices/Bookmark/BookmarkMicroservice.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 11549:8080
    depends_on:
      postgres-bookmark:
        condition: service_started
      gateway-api:
        condition: service_started
      kafka:
        condition: service_started

  employee-microservice-api:
    container_name: employee-microservice-api
    image: ${DOCKER_REGISTRY-}employeemicroservice-api
    build:
      context: .
      dockerfile: src/Microservices/Employee/EmployeeMicroservice.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 35124:8080
    depends_on:
      postgres-employee:
        condition: service_started
      gateway-api:
        condition: service_started
      kafka:
        condition: service_started

  employer-microservice-api:
    container_name: employer-microservice-api
    image: ${DOCKER_REGISTRY-}employermicroservice-api
    build:
      context: .
      dockerfile: src/Microservices/Employer/EmployerMicroservice.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 35125:8080
    depends_on:
      postgres-employer:
        condition: service_started
      gateway-api:
        condition: service_started
      kafka:
        condition: service_started

  company-microservice-api:
    container_name: company-microservice-api
    image: ${DOCKER_REGISTRY-}companymicroservice-api
    build:
      context: .
      dockerfile: src/Microservices/Company/CompanyMicroservice.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 35235:8080
    depends_on:
      postgres-company:
        condition: service_started
      gateway-api:
        condition: service_started
      kafka:
        condition: service_started

  vacancy-microservice-api:
    container_name: vacancy-microservice-api
    image: ${DOCKER_REGISTRY-}vacancymicroservice-api
    build:
      context: .
      dockerfile: src/Microservices/Vacancy/VacancyMicroservice.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 25912:8080
    depends_on:
      postgres-vacancy:
        condition: service_started
      gateway-api:
        condition: service_started
      kafka:
        condition: service_started

  resume-microservice-api:
    container_name: resume-microservice-api
    image: ${DOCKER_REGISTRY-}resumemicroservice-api
    build:
      context: .
      dockerfile: src/Microservices/Resume/ResumeMicroservice.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 22983:8080
    depends_on:
      postgres-resume:
        condition: service_started
      gateway-api:
        condition: service_started
      kafka:
        condition: service_started

  response-microservice-api:
    container_name: response-microservice-api
    image: ${DOCKER_REGISTRY-}responsemicroservice-api
    build:
      context: .
      dockerfile: src/Microservices/Response/ResponseMicroservice.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 21731:8080
    depends_on:
      postgres-response:
        condition: service_started
      gateway-api:
        condition: service_started
      kafka:
        condition: service_started

  chat-microservice-api:
    container_name: chat-microservice-api
    image: ${DOCKER_REGISTRY-}chat-microservice-api
    build:
      context: .
      dockerfile: src/Microservices/Chat/ChatMicroservice.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 21732:8080
    depends_on:
      postgres-chat:
        condition: service_started
      gateway-api:
        condition: service_started
      kafka:
        condition: service_started

  notification-microservice-api:
    image: ${DOCKER_REGISTRY-}notification-microservice-api
    container_name: notification-microservice-api
    build:
      context: .
      dockerfile: src/Microservices/Notification/NotificationMicroservice.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 38512:8080
    depends_on:
      postgres-notification:
        condition: service_started
      gateway-api:
        condition: service_started

  review-microservice-api:
    image: ${DOCKER_REGISTRY-}review-microservice-api
    container_name: review-microservice-api
    build:
      context: .
      dockerfile: src/Microservices/Review/ReviewMicroservice.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 37951:8080
    depends_on:
      postgres-review:
        condition: service_started
      gateway-api:
        condition: service_started

  postgres-review:
    container_name: postgres-review
    image: postgres:latest
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: JobFinderReviewMicroservice
    volumes: 
      - postgres-review-data:/var/lib/postgresql/data

  postgres-notification:
    container_name: postgres-notification
    image: postgres:latest
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: JobFinderNotificationMicroservice
    volumes: 
      - postgres-notification-data:/var/lib/postgresql/data

  postgres-chat:
    container_name: postgres-chat
    image: postgres:latest
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: JobFinderChatMicroservice
    volumes: 
      - postgres-chat-data:/var/lib/postgresql/data

  postgres-response:
    container_name: postgres-response
    image: postgres:latest
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: JobFinderResponseMicroservice
    volumes: 
      - postgres-response-data:/var/lib/postgresql/data

  postgres-bookmark:
    container_name: postgres-bookmark
    image: postgres:latest
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: JobFinderBookmarkMicroservice
    volumes: 
      - postgres-bookmark-data:/var/lib/postgresql/data

  postgres-resume:
    container_name: postgres-resume
    image: postgres:latest
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: JobFinderResumeMicroservice
    volumes: 
      - postgres-resume-data:/var/lib/postgresql/data

  postgres-vacancy:
    container_name: postgres-vacancy
    image: postgres:latest
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: JobFinderVacancyMicroservice
    volumes: 
      - postgres-vacancy-data:/var/lib/postgresql/data

  postgres-company:
    container_name: postgres-company
    image: postgres:latest
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: JobFinderCompanyMicroservice
    volumes: 
      - postgres-company-data:/var/lib/postgresql/data

  postgres-employer:
    container_name: postgres-employer
    image: postgres:latest
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: JobFinderEmployerMicroservice
    volumes: 
      - postgres-employer-data:/var/lib/postgresql/data

  postgres-account:
    container_name: postgres-account
    image: postgres:latest
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: JobFinderAccountMicroservice
    volumes: 
      - postgres-account-data:/var/lib/postgresql/data

  postgres-employee:
    container_name: postgres-employee
    image: postgres:latest
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: JobFinderEmployeeMicroservice
    volumes: 
      - postgres-employee-data:/var/lib/postgresql/data

  postgres-hangfire:
    container_name: postgres-hangfire
    image: postgres:latest
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: JobFinderHangfire
    volumes: 
      - postgres-hangfire-data:/var/lib/postgresql/data

  kafka:
    image: apache/kafka:latest
    hostname: kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


volumes:
  postgres-account-data: {}
  postgres-employee-data: {}
  postgres-employer-data: {}
  postgres-company-data: {}
  postgres-vacancy-data: {}
  postgres-resume-data: {}
  postgres-bookmark-data: {}
  postgres-response-data: {}
  postgres-hangfire-data: {}
  postgres-chat-data: {}
  postgres-notification-data: {}
  postgres-review-data: {}