services:
  web-mvc:
    container_name: web-mvc
    image: ${DOCKER_REGISTRY-}web-mvc
    build:
      context: .
      dockerfile: src/Web/Web.MVC/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 35121:8080

  gateway-api:
    container_name: gateway-api
    image: ${DOCKER_REGISTRY-}gateway-api
    build:
      context: .
      dockerfile: src/Gateway/Gateway.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 35122:8080

  account-microservice-api:
    container_name: account-microservice-api
    image: ${DOCKER_REGISTRY-}accountmicroservice-api
    build:
      context: .
      dockerfile: src/Microservices/Account/AccountMicroservice.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 35123:8080
    depends_on:
      - postgres-account
      - gateway-api
      - kafka

  employee-microservice-api:
    image: ${DOCKER_REGISTRY-}employeemicroservice-api
    container_name: employee-microservice-api
    build:
      context: .
      dockerfile: src/Microservices/Employee/EmployeeMicroservice.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 35124:8080
    depends_on:
      - postgres-employee
      - gateway-api
      - kafka

  employer-microservice-api:
    image: ${DOCKER_REGISTRY-}employermicroservice-api
    container_name: employer-microservice-api
    build:
      context: .
      dockerfile: src/Microservices/Employer/EmployerMicroservice.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 35125:8080
    depends_on:
      - postgres-employer
      - gateway-api
      - kafka

  postgres-employer:
    container_name: postgres-employer
    image: postgres:latest
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: JobFinderEmployerMicroservice
    volumes: 
      - postgres-employer-data:/var/lib/postgresql/data

  postgres-account:
    container_name: postgres-account
    image: postgres:latest
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: JobFinderAccountMicroservice
    volumes: 
      - postgres-account-data:/var/lib/postgresql/data

  postgres-employee:
    container_name: postgres-employee
    image: postgres:latest
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: JobFinderEmployeeMicroservice
    volumes: 
      - postgres-employee-data:/var/lib/postgresql/data

  zookeeper:
    hostname: zookeeper
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    container_name: kafka
    ports:
      - 9092:9092
      - 9094:9094
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper


volumes:
  postgres-account-data: {}
  postgres-employee-data: {}
  postgres-employer-data: {}